# Generated by Django 4.2 on 2023-04-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartwater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveles',
            name='fuente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='niveles',
            name='motor',
            field=models.BooleanField(default=False),
        ),
    ]
